# generated by datamodel-codegen:
#   filename:  manifest.v12.json
#   timestamp: 2024-12-07T11:29:08+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union
from uuid import UUID

from pydantic import BaseModel, Extra, Field


class Metadata(BaseModel):
    class Config:
        extra = Extra.forbid

    dbt_schema_version: Optional[str] = None
    dbt_version: Optional[str] = '1.9.0b4'
    generated_at: Optional[str] = None
    invocation_id: Optional[str] = None
    env: Optional[Dict[str, str]] = None
    project_name: Optional[str] = Field(None, description='Name of the root project')
    project_id: Optional[str] = Field(
        None, description='A unique identifier for the project, hashed from the project name'
    )
    user_id: Optional[UUID] = Field(None, description='A unique identifier for the user')
    send_anonymous_usage_stats: Optional[bool] = Field(
        None, description='Whether dbt is configured to send anonymous usage statistics'
    )
    adapter_type: Optional[str] = Field(None, description='The type name of the adapter')


class Checksum(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    checksum: str


class PostHookItem(BaseModel):
    class Config:
        extra = Extra.forbid

    sql: str
    transaction: Optional[bool] = True
    index: Optional[int] = None


class PreHookItem(PostHookItem):
    pass


class OnConfigurationChange(Enum):
    apply = 'apply'
    continue_ = 'continue'
    fail = 'fail'


class Docs(BaseModel):
    class Config:
        extra = Extra.forbid

    show: Optional[bool] = True
    node_color: Optional[str] = None


class Contract(BaseModel):
    class Config:
        extra = Extra.forbid

    enforced: Optional[bool] = False
    alias_types: Optional[bool] = True


class Config(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    enabled: Optional[bool] = True
    alias: Optional[str] = None
    schema_: Optional[str] = Field(None, alias='schema')
    database: Optional[str] = None
    tags: Optional[Union[List[str], str]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    materialized: Optional[str] = 'seed'
    incremental_strategy: Optional[str] = None
    batch_size: Optional[Any] = None
    lookback: Optional[Any] = 1
    begin: Optional[Any] = None
    persist_docs: Optional[Dict[str, Any]] = None
    post_hook: Optional[List[PostHookItem]] = Field(None, alias='post-hook')
    pre_hook: Optional[List[PreHookItem]] = Field(None, alias='pre-hook')
    quoting: Optional[Dict[str, Any]] = None
    column_types: Optional[Dict[str, Any]] = None
    full_refresh: Optional[bool] = None
    unique_key: Optional[Union[str, List[str]]] = None
    on_schema_change: Optional[str] = 'ignore'
    on_configuration_change: Optional[OnConfigurationChange] = None
    grants: Optional[Dict[str, Any]] = None
    packages: Optional[List[str]] = None
    docs: Optional[Docs] = Field(None, title='Docs')
    contract: Optional[Contract] = Field(None, title='ContractConfig')
    event_time: Optional[Any] = None
    concurrent_batches: Optional[Any] = None
    delimiter: Optional[str] = ','
    quote_columns: Optional[bool] = None


class Type(Enum):
    check = 'check'
    not_null = 'not_null'
    unique = 'unique'
    primary_key = 'primary_key'
    foreign_key = 'foreign_key'
    custom = 'custom'


class Constraint(BaseModel):
    class Config:
        extra = Extra.forbid

    type: Type
    name: Optional[str] = None
    expression: Optional[str] = None
    warn_unenforced: Optional[bool] = True
    warn_unsupported: Optional[bool] = True
    to: Optional[str] = None
    to_columns: Optional[List[str]] = None


class Granularity(Enum):
    nanosecond = 'nanosecond'
    microsecond = 'microsecond'
    millisecond = 'millisecond'
    second = 'second'
    minute = 'minute'
    hour = 'hour'
    day = 'day'
    week = 'week'
    month = 'month'
    quarter = 'quarter'
    year = 'year'


class Columns(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None
    data_type: Optional[str] = None
    constraints: Optional[List[Constraint]] = None
    quote: Optional[bool] = None
    tags: Optional[List[str]] = None
    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    granularity: Optional[Granularity] = None


class DependsOn(BaseModel):
    class Config:
        extra = Extra.forbid

    macros: Optional[List[str]] = None


class ResourceType(Enum):
    model = 'model'
    analysis = 'analysis'
    test = 'test'
    snapshot = 'snapshot'
    operation = 'operation'
    seed = 'seed'
    rpc = 'rpc'
    sql_operation = 'sql_operation'
    doc = 'doc'
    source = 'source'
    macro = 'macro'
    exposure = 'exposure'
    metric = 'metric'
    group = 'group'
    saved_query = 'saved_query'
    semantic_model = 'semantic_model'
    unit_test = 'unit_test'
    fixture = 'fixture'


class Config1(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    enabled: Optional[bool] = True
    alias: Optional[str] = None
    schema_: Optional[str] = Field(None, alias='schema')
    database: Optional[str] = None
    tags: Optional[Union[List[str], str]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    materialized: Optional[str] = 'view'
    incremental_strategy: Optional[str] = None
    batch_size: Optional[Any] = None
    lookback: Optional[Any] = 1
    begin: Optional[Any] = None
    persist_docs: Optional[Dict[str, Any]] = None
    post_hook: Optional[List[PostHookItem]] = Field(None, alias='post-hook')
    pre_hook: Optional[List[PreHookItem]] = Field(None, alias='pre-hook')
    quoting: Optional[Dict[str, Any]] = None
    column_types: Optional[Dict[str, Any]] = None
    full_refresh: Optional[bool] = None
    unique_key: Optional[Union[str, List[str]]] = None
    on_schema_change: Optional[str] = 'ignore'
    on_configuration_change: Optional[OnConfigurationChange] = None
    grants: Optional[Dict[str, Any]] = None
    packages: Optional[List[str]] = None
    docs: Optional[Docs] = Field(None, title='Docs')
    contract: Optional[Contract] = Field(None, title='ContractConfig')
    event_time: Optional[Any] = None
    concurrent_batches: Optional[Any] = None


class DeferRelation(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    alias: str
    relation_name: Optional[str]
    resource_type: ResourceType
    name: str
    description: str
    compiled_code: Optional[str]
    meta: Dict[str, Any]
    tags: List[str]
    config: Optional[Config1]


class Nodes(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    name: str
    resource_type: str = Field('seed', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    alias: str
    checksum: Checksum = Field(..., title='FileHash')
    config: Optional[Config] = Field(None, title='SeedConfig')
    tags: Optional[List[str]] = None
    description: Optional[str] = ''
    columns: Optional[Dict[str, Columns]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    docs: Optional[Docs] = Field(None, title='Docs')
    patch_path: Optional[str] = None
    build_path: Optional[str] = None
    unrendered_config: Optional[Dict[str, Any]] = None
    created_at: Optional[float] = None
    config_call_dict: Optional[Dict[str, Any]] = None
    unrendered_config_call_dict: Optional[Dict[str, Any]] = None
    relation_name: Optional[str] = None
    raw_code: Optional[str] = ''
    root_path: Optional[str] = None
    depends_on: Optional[DependsOn] = Field(None, title='MacroDependsOn')
    defer_relation: Optional[DeferRelation] = None


class Config2(Config1):
    pass


class Constraint1(Constraint):
    pass


class Columns1(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None
    data_type: Optional[str] = None
    constraints: Optional[List[Constraint1]] = None
    quote: Optional[bool] = None
    tags: Optional[List[str]] = None
    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    granularity: Optional[Granularity] = None


class Ref(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    package: Optional[str] = None
    version: Optional[Union[str, float]] = None


class DependsOn1(BaseModel):
    class Config:
        extra = Extra.forbid

    macros: Optional[List[str]] = None
    nodes: Optional[List[str]] = None


class ExtraCte(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str
    sql: str


class Contract3(BaseModel):
    class Config:
        extra = Extra.forbid

    enforced: Optional[bool] = False
    alias_types: Optional[bool] = True
    checksum: Optional[str] = None


class Nodes1(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    name: str
    resource_type: str = Field('analysis', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    alias: str
    checksum: Checksum = Field(..., title='FileHash')
    config: Optional[Config2] = Field(None, title='NodeConfig')
    tags: Optional[List[str]] = None
    description: Optional[str] = ''
    columns: Optional[Dict[str, Columns1]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    docs: Optional[Docs] = Field(None, title='Docs')
    patch_path: Optional[str] = None
    build_path: Optional[str] = None
    unrendered_config: Optional[Dict[str, Any]] = None
    created_at: Optional[float] = None
    config_call_dict: Optional[Dict[str, Any]] = None
    unrendered_config_call_dict: Optional[Dict[str, Any]] = None
    relation_name: Optional[str] = None
    raw_code: Optional[str] = ''
    language: Optional[str] = 'sql'
    refs: Optional[List[Ref]] = None
    sources: Optional[List[List[str]]] = None
    metrics: Optional[List[List[str]]] = None
    depends_on: Optional[DependsOn1] = Field(None, title='DependsOn')
    compiled_path: Optional[str] = None
    compiled: Optional[bool] = False
    compiled_code: Optional[str] = None
    extra_ctes_injected: Optional[bool] = False
    extra_ctes: Optional[List[ExtraCte]] = None
    field_pre_injected_sql: Optional[str] = Field(None, alias='_pre_injected_sql')
    contract: Optional[Contract3] = Field(None, title='Contract')


class Config3(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    enabled: Optional[bool] = True
    alias: Optional[str] = None
    schema_: Optional[str] = Field('dbt_test__audit', alias='schema')
    database: Optional[str] = None
    tags: Optional[Union[List[str], str]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    materialized: Optional[str] = 'test'
    severity: Optional[str] = Field('ERROR', regex='^([Ww][Aa][Rr][Nn]|[Ee][Rr][Rr][Oo][Rr])$')
    store_failures: Optional[bool] = None
    store_failures_as: Optional[str] = None
    where: Optional[str] = None
    limit: Optional[int] = None
    fail_calc: Optional[str] = 'count(*)'
    warn_if: Optional[str] = '!= 0'
    error_if: Optional[str] = '!= 0'


class Constraint2(Constraint):
    pass


class Columns2(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None
    data_type: Optional[str] = None
    constraints: Optional[List[Constraint2]] = None
    quote: Optional[bool] = None
    tags: Optional[List[str]] = None
    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    granularity: Optional[Granularity] = None


class Nodes2(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    name: str
    resource_type: str = Field('test', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    alias: str
    checksum: Checksum = Field(..., title='FileHash')
    config: Optional[Config3] = Field(None, title='TestConfig')
    tags: Optional[List[str]] = None
    description: Optional[str] = ''
    columns: Optional[Dict[str, Columns2]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    docs: Optional[Docs] = Field(None, title='Docs')
    patch_path: Optional[str] = None
    build_path: Optional[str] = None
    unrendered_config: Optional[Dict[str, Any]] = None
    created_at: Optional[float] = None
    config_call_dict: Optional[Dict[str, Any]] = None
    unrendered_config_call_dict: Optional[Dict[str, Any]] = None
    relation_name: Optional[str] = None
    raw_code: Optional[str] = ''
    language: Optional[str] = 'sql'
    refs: Optional[List[Ref]] = None
    sources: Optional[List[List[str]]] = None
    metrics: Optional[List[List[str]]] = None
    depends_on: Optional[DependsOn1] = Field(None, title='DependsOn')
    compiled_path: Optional[str] = None
    compiled: Optional[bool] = False
    compiled_code: Optional[str] = None
    extra_ctes_injected: Optional[bool] = False
    extra_ctes: Optional[List[ExtraCte]] = None
    field_pre_injected_sql: Optional[str] = Field(None, alias='_pre_injected_sql')
    contract: Optional[Contract3] = Field(None, title='Contract')


class Contract5(Contract):
    pass


class Config4(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    enabled: Optional[bool] = True
    alias: Optional[str] = None
    schema_: Optional[str] = Field(None, alias='schema')
    database: Optional[str] = None
    tags: Optional[Union[List[str], str]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    materialized: Optional[str] = 'view'
    incremental_strategy: Optional[str] = None
    batch_size: Optional[Any] = None
    lookback: Optional[Any] = 1
    begin: Optional[Any] = None
    persist_docs: Optional[Dict[str, Any]] = None
    post_hook: Optional[List[PostHookItem]] = Field(None, alias='post-hook')
    pre_hook: Optional[List[PreHookItem]] = Field(None, alias='pre-hook')
    quoting: Optional[Dict[str, Any]] = None
    column_types: Optional[Dict[str, Any]] = None
    full_refresh: Optional[bool] = None
    unique_key: Optional[Union[str, List[str]]] = None
    on_schema_change: Optional[str] = 'ignore'
    on_configuration_change: Optional[OnConfigurationChange] = None
    grants: Optional[Dict[str, Any]] = None
    packages: Optional[List[str]] = None
    docs: Optional[Docs] = Field(None, title='Docs')
    contract: Optional[Contract5] = Field(None, title='ContractConfig')
    event_time: Optional[Any] = None
    concurrent_batches: Optional[Any] = None


class Constraint3(Constraint):
    pass


class Columns3(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None
    data_type: Optional[str] = None
    constraints: Optional[List[Constraint3]] = None
    quote: Optional[bool] = None
    tags: Optional[List[str]] = None
    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    granularity: Optional[Granularity] = None


class Contract6(Contract3):
    pass


class Nodes3(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    name: str
    resource_type: str = Field('operation', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    alias: str
    checksum: Checksum = Field(..., title='FileHash')
    config: Optional[Config4] = Field(None, title='NodeConfig')
    tags: Optional[List[str]] = None
    description: Optional[str] = ''
    columns: Optional[Dict[str, Columns3]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    docs: Optional[Docs] = Field(None, title='Docs')
    patch_path: Optional[str] = None
    build_path: Optional[str] = None
    unrendered_config: Optional[Dict[str, Any]] = None
    created_at: Optional[float] = None
    config_call_dict: Optional[Dict[str, Any]] = None
    unrendered_config_call_dict: Optional[Dict[str, Any]] = None
    relation_name: Optional[str] = None
    raw_code: Optional[str] = ''
    language: Optional[str] = 'sql'
    refs: Optional[List[Ref]] = None
    sources: Optional[List[List[str]]] = None
    metrics: Optional[List[List[str]]] = None
    depends_on: Optional[DependsOn1] = Field(None, title='DependsOn')
    compiled_path: Optional[str] = None
    compiled: Optional[bool] = False
    compiled_code: Optional[str] = None
    extra_ctes_injected: Optional[bool] = False
    extra_ctes: Optional[List[ExtraCte]] = None
    field_pre_injected_sql: Optional[str] = Field(None, alias='_pre_injected_sql')
    contract: Optional[Contract6] = Field(None, title='Contract')
    index: Optional[int] = None


class Contract7(Contract):
    pass


class Access(Enum):
    private = 'private'
    protected = 'protected'
    public = 'public'


class Config5(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    enabled: Optional[bool] = True
    alias: Optional[str] = None
    schema_: Optional[str] = Field(None, alias='schema')
    database: Optional[str] = None
    tags: Optional[Union[List[str], str]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    materialized: Optional[str] = 'view'
    incremental_strategy: Optional[str] = None
    batch_size: Optional[Any] = None
    lookback: Optional[Any] = 1
    begin: Optional[Any] = None
    persist_docs: Optional[Dict[str, Any]] = None
    post_hook: Optional[List[PostHookItem]] = Field(None, alias='post-hook')
    pre_hook: Optional[List[PreHookItem]] = Field(None, alias='pre-hook')
    quoting: Optional[Dict[str, Any]] = None
    column_types: Optional[Dict[str, Any]] = None
    full_refresh: Optional[bool] = None
    unique_key: Optional[Union[str, List[str]]] = None
    on_schema_change: Optional[str] = 'ignore'
    on_configuration_change: Optional[OnConfigurationChange] = None
    grants: Optional[Dict[str, Any]] = None
    packages: Optional[List[str]] = None
    docs: Optional[Docs] = Field(None, title='Docs')
    contract: Optional[Contract7] = Field(None, title='ContractConfig')
    event_time: Optional[Any] = None
    concurrent_batches: Optional[Any] = None
    access: Optional[Access] = 'protected'


class Constraint4(Constraint):
    pass


class Columns4(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None
    data_type: Optional[str] = None
    constraints: Optional[List[Constraint4]] = None
    quote: Optional[bool] = None
    tags: Optional[List[str]] = None
    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    granularity: Optional[Granularity] = None


class Contract8(Contract3):
    pass


class Constraint5(BaseModel):
    class Config:
        extra = Extra.forbid

    type: Type
    name: Optional[str] = None
    expression: Optional[str] = None
    warn_unenforced: Optional[bool] = True
    warn_unsupported: Optional[bool] = True
    to: Optional[str] = None
    to_columns: Optional[List[str]] = None
    columns: Optional[List[str]] = None


class Contract9(Contract):
    pass


class Config6(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    enabled: Optional[bool] = True
    alias: Optional[str] = None
    schema_: Optional[str] = Field(None, alias='schema')
    database: Optional[str] = None
    tags: Optional[Union[List[str], str]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    materialized: Optional[str] = 'view'
    incremental_strategy: Optional[str] = None
    batch_size: Optional[Any] = None
    lookback: Optional[Any] = 1
    begin: Optional[Any] = None
    persist_docs: Optional[Dict[str, Any]] = None
    post_hook: Optional[List[PostHookItem]] = Field(None, alias='post-hook')
    pre_hook: Optional[List[PreHookItem]] = Field(None, alias='pre-hook')
    quoting: Optional[Dict[str, Any]] = None
    column_types: Optional[Dict[str, Any]] = None
    full_refresh: Optional[bool] = None
    unique_key: Optional[Union[str, List[str]]] = None
    on_schema_change: Optional[str] = 'ignore'
    on_configuration_change: Optional[OnConfigurationChange] = None
    grants: Optional[Dict[str, Any]] = None
    packages: Optional[List[str]] = None
    docs: Optional[Docs] = Field(None, title='Docs')
    contract: Optional[Contract9] = Field(None, title='ContractConfig')
    event_time: Optional[Any] = None
    concurrent_batches: Optional[Any] = None


class DeferRelation1(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    alias: str
    relation_name: Optional[str]
    resource_type: ResourceType
    name: str
    description: str
    compiled_code: Optional[str]
    meta: Dict[str, Any]
    tags: List[str]
    config: Optional[Config6]


class CustomGranularity(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    column_name: Optional[str] = None


class TimeSpine(BaseModel):
    class Config:
        extra = Extra.forbid

    standard_granularity_column: str
    custom_granularities: Optional[List[CustomGranularity]] = None


class Nodes4(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    name: str
    resource_type: str = Field('model', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    alias: str
    checksum: Checksum = Field(..., title='FileHash')
    config: Optional[Config5] = Field(None, title='ModelConfig')
    tags: Optional[List[str]] = None
    description: Optional[str] = ''
    columns: Optional[Dict[str, Columns4]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    docs: Optional[Docs] = Field(None, title='Docs')
    patch_path: Optional[str] = None
    build_path: Optional[str] = None
    unrendered_config: Optional[Dict[str, Any]] = None
    created_at: Optional[float] = None
    config_call_dict: Optional[Dict[str, Any]] = None
    unrendered_config_call_dict: Optional[Dict[str, Any]] = None
    relation_name: Optional[str] = None
    raw_code: Optional[str] = ''
    language: Optional[str] = 'sql'
    refs: Optional[List[Ref]] = None
    sources: Optional[List[List[str]]] = None
    metrics: Optional[List[List[str]]] = None
    depends_on: Optional[DependsOn1] = Field(None, title='DependsOn')
    compiled_path: Optional[str] = None
    compiled: Optional[bool] = False
    compiled_code: Optional[str] = None
    extra_ctes_injected: Optional[bool] = False
    extra_ctes: Optional[List[ExtraCte]] = None
    field_pre_injected_sql: Optional[str] = Field(None, alias='_pre_injected_sql')
    contract: Optional[Contract8] = Field(None, title='Contract')
    access: Optional[Access] = 'protected'
    constraints: Optional[List[Constraint5]] = None
    version: Optional[Union[str, float]] = None
    latest_version: Optional[Union[str, float]] = None
    deprecation_date: Optional[str] = None
    defer_relation: Optional[DeferRelation1] = None
    primary_key: Optional[List[str]] = None
    time_spine: Optional[TimeSpine] = None


class Config7(Config6):
    pass


class Constraint6(Constraint):
    pass


class Columns5(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None
    data_type: Optional[str] = None
    constraints: Optional[List[Constraint6]] = None
    quote: Optional[bool] = None
    tags: Optional[List[str]] = None
    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    granularity: Optional[Granularity] = None


class Contract11(Contract3):
    pass


class Nodes5(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    name: str
    resource_type: str = Field('sql_operation', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    alias: str
    checksum: Checksum = Field(..., title='FileHash')
    config: Optional[Config7] = Field(None, title='NodeConfig')
    tags: Optional[List[str]] = None
    description: Optional[str] = ''
    columns: Optional[Dict[str, Columns5]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    docs: Optional[Docs] = Field(None, title='Docs')
    patch_path: Optional[str] = None
    build_path: Optional[str] = None
    unrendered_config: Optional[Dict[str, Any]] = None
    created_at: Optional[float] = None
    config_call_dict: Optional[Dict[str, Any]] = None
    unrendered_config_call_dict: Optional[Dict[str, Any]] = None
    relation_name: Optional[str] = None
    raw_code: Optional[str] = ''
    language: Optional[str] = 'sql'
    refs: Optional[List[Ref]] = None
    sources: Optional[List[List[str]]] = None
    metrics: Optional[List[List[str]]] = None
    depends_on: Optional[DependsOn1] = Field(None, title='DependsOn')
    compiled_path: Optional[str] = None
    compiled: Optional[bool] = False
    compiled_code: Optional[str] = None
    extra_ctes_injected: Optional[bool] = False
    extra_ctes: Optional[List[ExtraCte]] = None
    field_pre_injected_sql: Optional[str] = Field(None, alias='_pre_injected_sql')
    contract: Optional[Contract11] = Field(None, title='Contract')


class Config8(Config3):
    pass


class Constraint7(Constraint):
    pass


class Columns6(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None
    data_type: Optional[str] = None
    constraints: Optional[List[Constraint7]] = None
    quote: Optional[bool] = None
    tags: Optional[List[str]] = None
    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    granularity: Optional[Granularity] = None


class TestMetadata(BaseModel):
    class Config:
        extra = Extra.forbid

    name: Optional[str] = 'test'
    kwargs: Optional[Dict[str, Any]] = None
    namespace: Optional[str] = None


class Nodes6(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    name: str
    resource_type: str = Field('test', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    alias: str
    checksum: Checksum = Field(..., title='FileHash')
    config: Optional[Config8] = Field(None, title='TestConfig')
    tags: Optional[List[str]] = None
    description: Optional[str] = ''
    columns: Optional[Dict[str, Columns6]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    docs: Optional[Docs] = Field(None, title='Docs')
    patch_path: Optional[str] = None
    build_path: Optional[str] = None
    unrendered_config: Optional[Dict[str, Any]] = None
    created_at: Optional[float] = None
    config_call_dict: Optional[Dict[str, Any]] = None
    unrendered_config_call_dict: Optional[Dict[str, Any]] = None
    relation_name: Optional[str] = None
    raw_code: Optional[str] = ''
    language: Optional[str] = 'sql'
    refs: Optional[List[Ref]] = None
    sources: Optional[List[List[str]]] = None
    metrics: Optional[List[List[str]]] = None
    depends_on: Optional[DependsOn1] = Field(None, title='DependsOn')
    compiled_path: Optional[str] = None
    compiled: Optional[bool] = False
    compiled_code: Optional[str] = None
    extra_ctes_injected: Optional[bool] = False
    extra_ctes: Optional[List[ExtraCte]] = None
    field_pre_injected_sql: Optional[str] = Field(None, alias='_pre_injected_sql')
    contract: Optional[Contract11] = Field(None, title='Contract')
    column_name: Optional[str] = None
    file_key_name: Optional[str] = None
    attached_node: Optional[str] = None
    test_metadata: Optional[TestMetadata] = Field(None, title='TestMetadata')


class Contract13(Contract):
    pass


class SnapshotMetaColumnNames(BaseModel):
    class Config:
        extra = Extra.forbid

    dbt_valid_to: Optional[str] = None
    dbt_valid_from: Optional[str] = None
    dbt_scd_id: Optional[str] = None
    dbt_updated_at: Optional[str] = None
    dbt_is_deleted: Optional[str] = None


class Config9(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    enabled: Optional[bool] = True
    alias: Optional[str] = None
    schema_: Optional[str] = Field(None, alias='schema')
    database: Optional[str] = None
    tags: Optional[Union[List[str], str]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    materialized: Optional[str] = 'snapshot'
    incremental_strategy: Optional[str] = None
    batch_size: Optional[Any] = None
    lookback: Optional[Any] = 1
    begin: Optional[Any] = None
    persist_docs: Optional[Dict[str, Any]] = None
    post_hook: Optional[List[PostHookItem]] = Field(None, alias='post-hook')
    pre_hook: Optional[List[PreHookItem]] = Field(None, alias='pre-hook')
    quoting: Optional[Dict[str, Any]] = None
    column_types: Optional[Dict[str, Any]] = None
    full_refresh: Optional[bool] = None
    unique_key: Optional[Union[str, List[str]]] = None
    on_schema_change: Optional[str] = 'ignore'
    on_configuration_change: Optional[OnConfigurationChange] = None
    grants: Optional[Dict[str, Any]] = None
    packages: Optional[List[str]] = None
    docs: Optional[Docs] = Field(None, title='Docs')
    contract: Optional[Contract13] = Field(None, title='ContractConfig')
    event_time: Optional[Any] = None
    concurrent_batches: Optional[Any] = None
    strategy: Optional[str] = None
    target_schema: Optional[str] = None
    target_database: Optional[str] = None
    updated_at: Optional[str] = None
    check_cols: Optional[Union[str, List[str]]] = None
    snapshot_meta_column_names: Optional[SnapshotMetaColumnNames] = Field(
        None, title='SnapshotMetaColumnNames'
    )
    dbt_valid_to_current: Optional[str] = None


class Constraint8(Constraint):
    pass


class Columns7(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None
    data_type: Optional[str] = None
    constraints: Optional[List[Constraint8]] = None
    quote: Optional[bool] = None
    tags: Optional[List[str]] = None
    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    granularity: Optional[Granularity] = None


class Contract14(Contract3):
    pass


class Contract15(Contract):
    pass


class Config10(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    enabled: Optional[bool] = True
    alias: Optional[str] = None
    schema_: Optional[str] = Field(None, alias='schema')
    database: Optional[str] = None
    tags: Optional[Union[List[str], str]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    materialized: Optional[str] = 'view'
    incremental_strategy: Optional[str] = None
    batch_size: Optional[Any] = None
    lookback: Optional[Any] = 1
    begin: Optional[Any] = None
    persist_docs: Optional[Dict[str, Any]] = None
    post_hook: Optional[List[PostHookItem]] = Field(None, alias='post-hook')
    pre_hook: Optional[List[PreHookItem]] = Field(None, alias='pre-hook')
    quoting: Optional[Dict[str, Any]] = None
    column_types: Optional[Dict[str, Any]] = None
    full_refresh: Optional[bool] = None
    unique_key: Optional[Union[str, List[str]]] = None
    on_schema_change: Optional[str] = 'ignore'
    on_configuration_change: Optional[OnConfigurationChange] = None
    grants: Optional[Dict[str, Any]] = None
    packages: Optional[List[str]] = None
    docs: Optional[Docs] = Field(None, title='Docs')
    contract: Optional[Contract15] = Field(None, title='ContractConfig')
    event_time: Optional[Any] = None
    concurrent_batches: Optional[Any] = None


class DeferRelation2(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    alias: str
    relation_name: Optional[str]
    resource_type: ResourceType
    name: str
    description: str
    compiled_code: Optional[str]
    meta: Dict[str, Any]
    tags: List[str]
    config: Optional[Config10]


class Nodes7(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    name: str
    resource_type: str = Field('snapshot', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    alias: str
    checksum: Checksum = Field(..., title='FileHash')
    config: Config9 = Field(..., title='SnapshotConfig')
    tags: Optional[List[str]] = None
    description: Optional[str] = ''
    columns: Optional[Dict[str, Columns7]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    docs: Optional[Docs] = Field(None, title='Docs')
    patch_path: Optional[str] = None
    build_path: Optional[str] = None
    unrendered_config: Optional[Dict[str, Any]] = None
    created_at: Optional[float] = None
    config_call_dict: Optional[Dict[str, Any]] = None
    unrendered_config_call_dict: Optional[Dict[str, Any]] = None
    relation_name: Optional[str] = None
    raw_code: Optional[str] = ''
    language: Optional[str] = 'sql'
    refs: Optional[List[Ref]] = None
    sources: Optional[List[List[str]]] = None
    metrics: Optional[List[List[str]]] = None
    depends_on: Optional[DependsOn1] = Field(None, title='DependsOn')
    compiled_path: Optional[str] = None
    compiled: Optional[bool] = False
    compiled_code: Optional[str] = None
    extra_ctes_injected: Optional[bool] = False
    extra_ctes: Optional[List[ExtraCte]] = None
    field_pre_injected_sql: Optional[str] = Field(None, alias='_pre_injected_sql')
    contract: Optional[Contract14] = Field(None, title='Contract')
    defer_relation: Optional[DeferRelation2] = None


class Quoting(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[bool] = None
    schema_: Optional[bool] = Field(None, alias='schema')
    identifier: Optional[bool] = None
    column: Optional[bool] = None


class Period(Enum):
    minute = 'minute'
    hour = 'hour'
    day = 'day'


class WarnAfter(BaseModel):
    class Config:
        extra = Extra.forbid

    count: Optional[int] = None
    period: Optional[Period] = None


class ErrorAfter(WarnAfter):
    pass


class Freshness(BaseModel):
    class Config:
        extra = Extra.forbid

    warn_after: Optional[WarnAfter] = None
    error_after: Optional[ErrorAfter] = None
    filter: Optional[str] = None


class Partition(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    name: Optional[str] = ''
    description: Optional[str] = ''
    data_type: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None


class External(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    location: Optional[str] = None
    file_format: Optional[str] = None
    row_format: Optional[str] = None
    tbl_properties: Optional[str] = None
    partitions: Optional[Union[List[str], List[Partition]]] = None


class Constraint9(Constraint):
    pass


class Columns8(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None
    data_type: Optional[str] = None
    constraints: Optional[List[Constraint9]] = None
    quote: Optional[bool] = None
    tags: Optional[List[str]] = None
    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    granularity: Optional[Granularity] = None


class Config11(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    enabled: Optional[bool] = True
    event_time: Optional[Any] = None


class Sources(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    name: str
    resource_type: str = Field('source', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    source_name: str
    source_description: str
    loader: str
    identifier: str
    quoting: Optional[Quoting] = Field(None, title='Quoting')
    loaded_at_field: Optional[str] = None
    freshness: Optional[Freshness] = None
    external: Optional[External] = None
    description: Optional[str] = ''
    columns: Optional[Dict[str, Columns8]] = None
    meta: Optional[Dict[str, Any]] = None
    source_meta: Optional[Dict[str, Any]] = None
    tags: Optional[List[str]] = None
    config: Optional[Config11] = Field(None, title='SourceConfig')
    patch_path: Optional[str] = None
    unrendered_config: Optional[Dict[str, Any]] = None
    relation_name: Optional[str] = None
    created_at: Optional[float] = None
    unrendered_database: Optional[str] = None
    unrendered_schema: Optional[str] = None


class DependsOn8(DependsOn):
    pass


class Argument(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    type: Optional[str] = None
    description: Optional[str] = ''


class SupportedLanguage(Enum):
    python = 'python'
    sql = 'sql'


class Macros(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    resource_type: str = Field('macro', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    macro_sql: str
    depends_on: Optional[DependsOn8] = Field(None, title='MacroDependsOn')
    description: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None
    docs: Optional[Docs] = Field(None, title='Docs')
    patch_path: Optional[str] = None
    arguments: Optional[List[Argument]] = None
    created_at: Optional[float] = None
    supported_languages: Optional[List[SupportedLanguage]] = None


class Docs18(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    resource_type: str = Field('doc', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    block_contents: str


class Type10(Enum):
    dashboard = 'dashboard'
    notebook = 'notebook'
    analysis = 'analysis'
    ml = 'ml'
    application = 'application'


class Owner(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    email: Optional[str] = None
    name: Optional[str] = None


class Maturity(Enum):
    low = 'low'
    medium = 'medium'
    high = 'high'


class Config12(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    enabled: Optional[bool] = True


class DependsOn9(DependsOn1):
    pass


class Exposures(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    resource_type: str = Field('exposure', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    type: Type10
    owner: Owner = Field(..., title='Owner')
    description: Optional[str] = ''
    label: Optional[str] = None
    maturity: Optional[Maturity] = None
    meta: Optional[Dict[str, Any]] = None
    tags: Optional[List[str]] = None
    config: Optional[Config12] = Field(None, title='ExposureConfig')
    unrendered_config: Optional[Dict[str, Any]] = None
    url: Optional[str] = None
    depends_on: Optional[DependsOn9] = Field(None, title='DependsOn')
    refs: Optional[List[Ref]] = None
    sources: Optional[List[List[str]]] = None
    metrics: Optional[List[List[str]]] = None
    created_at: Optional[float] = None


class Type11(Enum):
    simple = 'simple'
    ratio = 'ratio'
    cumulative = 'cumulative'
    derived = 'derived'
    conversion = 'conversion'


class WhereFilter(BaseModel):
    class Config:
        extra = Extra.forbid

    where_sql_template: str


class Filter(BaseModel):
    class Config:
        extra = Extra.forbid

    where_filters: List[WhereFilter]


class Measure(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    filter: Optional[Filter] = None
    alias: Optional[str] = None
    join_to_timespine: Optional[bool] = False
    fill_nulls_with: Optional[int] = None


class Filter1(Filter):
    pass


class InputMeasure(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    filter: Optional[Filter1] = None
    alias: Optional[str] = None
    join_to_timespine: Optional[bool] = False
    fill_nulls_with: Optional[int] = None


class Filter2(Filter):
    pass


class OffsetWindow(BaseModel):
    class Config:
        extra = Extra.forbid

    count: int
    granularity: str


class Numerator(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    filter: Optional[Filter2] = None
    alias: Optional[str] = None
    offset_window: Optional[OffsetWindow] = None
    offset_to_grain: Optional[str] = None


class Filter3(Filter):
    pass


class Denominator(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    filter: Optional[Filter3] = None
    alias: Optional[str] = None
    offset_window: Optional[OffsetWindow] = None
    offset_to_grain: Optional[str] = None


class Window(BaseModel):
    class Config:
        extra = Extra.forbid

    count: int
    granularity: Granularity


class Filter4(Filter):
    pass


class Metric(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    filter: Optional[Filter4] = None
    alias: Optional[str] = None
    offset_window: Optional[OffsetWindow] = None
    offset_to_grain: Optional[str] = None


class Filter5(Filter):
    pass


class BaseMeasure(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    filter: Optional[Filter5] = None
    alias: Optional[str] = None
    join_to_timespine: Optional[bool] = False
    fill_nulls_with: Optional[int] = None


class Filter6(Filter):
    pass


class ConversionMeasure(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    filter: Optional[Filter6] = None
    alias: Optional[str] = None
    join_to_timespine: Optional[bool] = False
    fill_nulls_with: Optional[int] = None


class Calculation(Enum):
    conversions = 'conversions'
    conversion_rate = 'conversion_rate'


class Window1(OffsetWindow):
    pass


class ConstantProperty(BaseModel):
    class Config:
        extra = Extra.forbid

    base_property: str
    conversion_property: str


class ConversionTypeParams(BaseModel):
    class Config:
        extra = Extra.forbid

    base_measure: BaseMeasure = Field(..., title='MetricInputMeasure')
    conversion_measure: ConversionMeasure = Field(..., title='MetricInputMeasure')
    entity: str
    calculation: Optional[Calculation] = 'conversion_rate'
    window: Optional[Window1] = None
    constant_properties: Optional[List[ConstantProperty]] = None


class PeriodAgg(Enum):
    first = 'first'
    last = 'last'
    average = 'average'


class CumulativeTypeParams(BaseModel):
    class Config:
        extra = Extra.forbid

    window: Optional[Window1] = None
    grain_to_date: Optional[str] = None
    period_agg: Optional[PeriodAgg] = 'first'


class TypeParams(BaseModel):
    class Config:
        extra = Extra.forbid

    measure: Optional[Measure] = None
    input_measures: Optional[List[InputMeasure]] = None
    numerator: Optional[Numerator] = None
    denominator: Optional[Denominator] = None
    expr: Optional[str] = None
    window: Optional[Window] = None
    grain_to_date: Optional[Granularity] = None
    metrics: Optional[List[Metric]] = None
    conversion_type_params: Optional[ConversionTypeParams] = None
    cumulative_type_params: Optional[CumulativeTypeParams] = None


class Filter7(Filter):
    pass


class FileSlice(BaseModel):
    class Config:
        extra = Extra.forbid

    filename: str
    content: str
    start_line_number: int
    end_line_number: int


class Metadata1(BaseModel):
    class Config:
        extra = Extra.forbid

    repo_file_path: str
    file_slice: FileSlice = Field(..., title='FileSlice')


class Config13(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    enabled: Optional[bool] = True
    group: Optional[str] = None
    meta: Optional[Dict[str, Any]] = None


class Metrics(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    resource_type: str = Field('metric', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    description: str
    label: str
    type: Type11
    type_params: TypeParams = Field(..., title='MetricTypeParams')
    filter: Optional[Filter7] = None
    metadata: Optional[Metadata1] = None
    time_granularity: Optional[str] = None
    meta: Optional[Dict[str, Any]] = None
    tags: Optional[List[str]] = None
    config: Optional[Config13] = Field(None, title='MetricConfig')
    unrendered_config: Optional[Dict[str, Any]] = None
    sources: Optional[List[List[str]]] = None
    depends_on: Optional[DependsOn9] = Field(None, title='DependsOn')
    refs: Optional[List[Ref]] = None
    metrics: Optional[List[List[str]]] = None
    created_at: Optional[float] = None
    group: Optional[str] = None


class Groups(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    resource_type: str = Field('group', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    owner: Owner = Field(..., title='Owner')


class Docs19(Docs):
    pass


class Config14(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    enabled: Optional[bool] = True
    alias: Optional[str] = None
    schema_: Optional[str] = Field(None, alias='schema')
    database: Optional[str] = None
    tags: Optional[Union[List[str], str]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    materialized: Optional[str] = 'seed'
    incremental_strategy: Optional[str] = None
    batch_size: Optional[Any] = None
    lookback: Optional[Any] = 1
    begin: Optional[Any] = None
    persist_docs: Optional[Dict[str, Any]] = None
    post_hook: Optional[List[PostHookItem]] = Field(None, alias='post-hook')
    pre_hook: Optional[List[PreHookItem]] = Field(None, alias='pre-hook')
    quoting: Optional[Dict[str, Any]] = None
    column_types: Optional[Dict[str, Any]] = None
    full_refresh: Optional[bool] = None
    unique_key: Optional[Union[str, List[str]]] = None
    on_schema_change: Optional[str] = 'ignore'
    on_configuration_change: Optional[OnConfigurationChange] = None
    grants: Optional[Dict[str, Any]] = None
    packages: Optional[List[str]] = None
    docs: Optional[Docs19] = Field(None, title='Docs')
    contract: Optional[Contract15] = Field(None, title='ContractConfig')
    event_time: Optional[Any] = None
    concurrent_batches: Optional[Any] = None
    delimiter: Optional[str] = ','
    quote_columns: Optional[bool] = None


class Constraint10(Constraint):
    pass


class Columns9(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None
    data_type: Optional[str] = None
    constraints: Optional[List[Constraint10]] = None
    quote: Optional[bool] = None
    tags: Optional[List[str]] = None
    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    granularity: Optional[Granularity] = None


class DependsOn11(DependsOn):
    pass


class Config15(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    enabled: Optional[bool] = True
    alias: Optional[str] = None
    schema_: Optional[str] = Field(None, alias='schema')
    database: Optional[str] = None
    tags: Optional[Union[List[str], str]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    materialized: Optional[str] = 'view'
    incremental_strategy: Optional[str] = None
    batch_size: Optional[Any] = None
    lookback: Optional[Any] = 1
    begin: Optional[Any] = None
    persist_docs: Optional[Dict[str, Any]] = None
    post_hook: Optional[List[PostHookItem]] = Field(None, alias='post-hook')
    pre_hook: Optional[List[PreHookItem]] = Field(None, alias='pre-hook')
    quoting: Optional[Dict[str, Any]] = None
    column_types: Optional[Dict[str, Any]] = None
    full_refresh: Optional[bool] = None
    unique_key: Optional[Union[str, List[str]]] = None
    on_schema_change: Optional[str] = 'ignore'
    on_configuration_change: Optional[OnConfigurationChange] = None
    grants: Optional[Dict[str, Any]] = None
    packages: Optional[List[str]] = None
    docs: Optional[Docs19] = Field(None, title='Docs')
    contract: Optional[Contract15] = Field(None, title='ContractConfig')
    event_time: Optional[Any] = None
    concurrent_batches: Optional[Any] = None


class DeferRelation3(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    alias: str
    relation_name: Optional[str]
    resource_type: ResourceType
    name: str
    description: str
    compiled_code: Optional[str]
    meta: Dict[str, Any]
    tags: List[str]
    config: Optional[Config15]


class Disabled(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    name: str
    resource_type: str = Field('seed', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    alias: str
    checksum: Checksum = Field(..., title='FileHash')
    config: Optional[Config14] = Field(None, title='SeedConfig')
    tags: Optional[List[str]] = None
    description: Optional[str] = ''
    columns: Optional[Dict[str, Columns9]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    docs: Optional[Docs19] = Field(None, title='Docs')
    patch_path: Optional[str] = None
    build_path: Optional[str] = None
    unrendered_config: Optional[Dict[str, Any]] = None
    created_at: Optional[float] = None
    config_call_dict: Optional[Dict[str, Any]] = None
    unrendered_config_call_dict: Optional[Dict[str, Any]] = None
    relation_name: Optional[str] = None
    raw_code: Optional[str] = ''
    root_path: Optional[str] = None
    depends_on: Optional[DependsOn11] = Field(None, title='MacroDependsOn')
    defer_relation: Optional[DeferRelation3] = None


class Config16(Config15):
    pass


class Constraint11(Constraint):
    pass


class Columns10(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None
    data_type: Optional[str] = None
    constraints: Optional[List[Constraint11]] = None
    quote: Optional[bool] = None
    tags: Optional[List[str]] = None
    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    granularity: Optional[Granularity] = None


class DependsOn12(DependsOn1):
    pass


class Contract19(Contract3):
    pass


class Disabled1(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    name: str
    resource_type: str = Field('analysis', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    alias: str
    checksum: Checksum = Field(..., title='FileHash')
    config: Optional[Config16] = Field(None, title='NodeConfig')
    tags: Optional[List[str]] = None
    description: Optional[str] = ''
    columns: Optional[Dict[str, Columns10]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    docs: Optional[Docs19] = Field(None, title='Docs')
    patch_path: Optional[str] = None
    build_path: Optional[str] = None
    unrendered_config: Optional[Dict[str, Any]] = None
    created_at: Optional[float] = None
    config_call_dict: Optional[Dict[str, Any]] = None
    unrendered_config_call_dict: Optional[Dict[str, Any]] = None
    relation_name: Optional[str] = None
    raw_code: Optional[str] = ''
    language: Optional[str] = 'sql'
    refs: Optional[List[Ref]] = None
    sources: Optional[List[List[str]]] = None
    metrics: Optional[List[List[str]]] = None
    depends_on: Optional[DependsOn12] = Field(None, title='DependsOn')
    compiled_path: Optional[str] = None
    compiled: Optional[bool] = False
    compiled_code: Optional[str] = None
    extra_ctes_injected: Optional[bool] = False
    extra_ctes: Optional[List[ExtraCte]] = None
    field_pre_injected_sql: Optional[str] = Field(None, alias='_pre_injected_sql')
    contract: Optional[Contract19] = Field(None, title='Contract')


class Config17(Config3):
    pass


class Constraint12(Constraint):
    pass


class Columns11(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None
    data_type: Optional[str] = None
    constraints: Optional[List[Constraint12]] = None
    quote: Optional[bool] = None
    tags: Optional[List[str]] = None
    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    granularity: Optional[Granularity] = None


class Disabled2(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    name: str
    resource_type: str = Field('test', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    alias: str
    checksum: Checksum = Field(..., title='FileHash')
    config: Optional[Config17] = Field(None, title='TestConfig')
    tags: Optional[List[str]] = None
    description: Optional[str] = ''
    columns: Optional[Dict[str, Columns11]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    docs: Optional[Docs19] = Field(None, title='Docs')
    patch_path: Optional[str] = None
    build_path: Optional[str] = None
    unrendered_config: Optional[Dict[str, Any]] = None
    created_at: Optional[float] = None
    config_call_dict: Optional[Dict[str, Any]] = None
    unrendered_config_call_dict: Optional[Dict[str, Any]] = None
    relation_name: Optional[str] = None
    raw_code: Optional[str] = ''
    language: Optional[str] = 'sql'
    refs: Optional[List[Ref]] = None
    sources: Optional[List[List[str]]] = None
    metrics: Optional[List[List[str]]] = None
    depends_on: Optional[DependsOn12] = Field(None, title='DependsOn')
    compiled_path: Optional[str] = None
    compiled: Optional[bool] = False
    compiled_code: Optional[str] = None
    extra_ctes_injected: Optional[bool] = False
    extra_ctes: Optional[List[ExtraCte]] = None
    field_pre_injected_sql: Optional[str] = Field(None, alias='_pre_injected_sql')
    contract: Optional[Contract19] = Field(None, title='Contract')


class Contract21(Contract):
    pass


class Config18(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    enabled: Optional[bool] = True
    alias: Optional[str] = None
    schema_: Optional[str] = Field(None, alias='schema')
    database: Optional[str] = None
    tags: Optional[Union[List[str], str]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    materialized: Optional[str] = 'view'
    incremental_strategy: Optional[str] = None
    batch_size: Optional[Any] = None
    lookback: Optional[Any] = 1
    begin: Optional[Any] = None
    persist_docs: Optional[Dict[str, Any]] = None
    post_hook: Optional[List[PostHookItem]] = Field(None, alias='post-hook')
    pre_hook: Optional[List[PreHookItem]] = Field(None, alias='pre-hook')
    quoting: Optional[Dict[str, Any]] = None
    column_types: Optional[Dict[str, Any]] = None
    full_refresh: Optional[bool] = None
    unique_key: Optional[Union[str, List[str]]] = None
    on_schema_change: Optional[str] = 'ignore'
    on_configuration_change: Optional[OnConfigurationChange] = None
    grants: Optional[Dict[str, Any]] = None
    packages: Optional[List[str]] = None
    docs: Optional[Docs19] = Field(None, title='Docs')
    contract: Optional[Contract21] = Field(None, title='ContractConfig')
    event_time: Optional[Any] = None
    concurrent_batches: Optional[Any] = None


class Constraint13(Constraint):
    pass


class Columns12(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None
    data_type: Optional[str] = None
    constraints: Optional[List[Constraint13]] = None
    quote: Optional[bool] = None
    tags: Optional[List[str]] = None
    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    granularity: Optional[Granularity] = None


class Contract22(Contract3):
    pass


class Disabled3(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    name: str
    resource_type: str = Field('operation', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    alias: str
    checksum: Checksum = Field(..., title='FileHash')
    config: Optional[Config18] = Field(None, title='NodeConfig')
    tags: Optional[List[str]] = None
    description: Optional[str] = ''
    columns: Optional[Dict[str, Columns12]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    docs: Optional[Docs19] = Field(None, title='Docs')
    patch_path: Optional[str] = None
    build_path: Optional[str] = None
    unrendered_config: Optional[Dict[str, Any]] = None
    created_at: Optional[float] = None
    config_call_dict: Optional[Dict[str, Any]] = None
    unrendered_config_call_dict: Optional[Dict[str, Any]] = None
    relation_name: Optional[str] = None
    raw_code: Optional[str] = ''
    language: Optional[str] = 'sql'
    refs: Optional[List[Ref]] = None
    sources: Optional[List[List[str]]] = None
    metrics: Optional[List[List[str]]] = None
    depends_on: Optional[DependsOn12] = Field(None, title='DependsOn')
    compiled_path: Optional[str] = None
    compiled: Optional[bool] = False
    compiled_code: Optional[str] = None
    extra_ctes_injected: Optional[bool] = False
    extra_ctes: Optional[List[ExtraCte]] = None
    field_pre_injected_sql: Optional[str] = Field(None, alias='_pre_injected_sql')
    contract: Optional[Contract22] = Field(None, title='Contract')
    index: Optional[int] = None


class Contract23(Contract):
    pass


class Config19(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    enabled: Optional[bool] = True
    alias: Optional[str] = None
    schema_: Optional[str] = Field(None, alias='schema')
    database: Optional[str] = None
    tags: Optional[Union[List[str], str]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    materialized: Optional[str] = 'view'
    incremental_strategy: Optional[str] = None
    batch_size: Optional[Any] = None
    lookback: Optional[Any] = 1
    begin: Optional[Any] = None
    persist_docs: Optional[Dict[str, Any]] = None
    post_hook: Optional[List[PostHookItem]] = Field(None, alias='post-hook')
    pre_hook: Optional[List[PreHookItem]] = Field(None, alias='pre-hook')
    quoting: Optional[Dict[str, Any]] = None
    column_types: Optional[Dict[str, Any]] = None
    full_refresh: Optional[bool] = None
    unique_key: Optional[Union[str, List[str]]] = None
    on_schema_change: Optional[str] = 'ignore'
    on_configuration_change: Optional[OnConfigurationChange] = None
    grants: Optional[Dict[str, Any]] = None
    packages: Optional[List[str]] = None
    docs: Optional[Docs19] = Field(None, title='Docs')
    contract: Optional[Contract23] = Field(None, title='ContractConfig')
    event_time: Optional[Any] = None
    concurrent_batches: Optional[Any] = None
    access: Optional[Access] = 'protected'


class Constraint14(Constraint):
    pass


class Columns13(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None
    data_type: Optional[str] = None
    constraints: Optional[List[Constraint14]] = None
    quote: Optional[bool] = None
    tags: Optional[List[str]] = None
    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    granularity: Optional[Granularity] = None


class Contract24(Contract3):
    pass


class Constraint15(Constraint5):
    pass


class Contract25(Contract):
    pass


class Config20(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    enabled: Optional[bool] = True
    alias: Optional[str] = None
    schema_: Optional[str] = Field(None, alias='schema')
    database: Optional[str] = None
    tags: Optional[Union[List[str], str]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    materialized: Optional[str] = 'view'
    incremental_strategy: Optional[str] = None
    batch_size: Optional[Any] = None
    lookback: Optional[Any] = 1
    begin: Optional[Any] = None
    persist_docs: Optional[Dict[str, Any]] = None
    post_hook: Optional[List[PostHookItem]] = Field(None, alias='post-hook')
    pre_hook: Optional[List[PreHookItem]] = Field(None, alias='pre-hook')
    quoting: Optional[Dict[str, Any]] = None
    column_types: Optional[Dict[str, Any]] = None
    full_refresh: Optional[bool] = None
    unique_key: Optional[Union[str, List[str]]] = None
    on_schema_change: Optional[str] = 'ignore'
    on_configuration_change: Optional[OnConfigurationChange] = None
    grants: Optional[Dict[str, Any]] = None
    packages: Optional[List[str]] = None
    docs: Optional[Docs19] = Field(None, title='Docs')
    contract: Optional[Contract25] = Field(None, title='ContractConfig')
    event_time: Optional[Any] = None
    concurrent_batches: Optional[Any] = None


class DeferRelation4(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    alias: str
    relation_name: Optional[str]
    resource_type: ResourceType
    name: str
    description: str
    compiled_code: Optional[str]
    meta: Dict[str, Any]
    tags: List[str]
    config: Optional[Config20]


class TimeSpine1(TimeSpine):
    pass


class Disabled4(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    name: str
    resource_type: str = Field('model', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    alias: str
    checksum: Checksum = Field(..., title='FileHash')
    config: Optional[Config19] = Field(None, title='ModelConfig')
    tags: Optional[List[str]] = None
    description: Optional[str] = ''
    columns: Optional[Dict[str, Columns13]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    docs: Optional[Docs19] = Field(None, title='Docs')
    patch_path: Optional[str] = None
    build_path: Optional[str] = None
    unrendered_config: Optional[Dict[str, Any]] = None
    created_at: Optional[float] = None
    config_call_dict: Optional[Dict[str, Any]] = None
    unrendered_config_call_dict: Optional[Dict[str, Any]] = None
    relation_name: Optional[str] = None
    raw_code: Optional[str] = ''
    language: Optional[str] = 'sql'
    refs: Optional[List[Ref]] = None
    sources: Optional[List[List[str]]] = None
    metrics: Optional[List[List[str]]] = None
    depends_on: Optional[DependsOn12] = Field(None, title='DependsOn')
    compiled_path: Optional[str] = None
    compiled: Optional[bool] = False
    compiled_code: Optional[str] = None
    extra_ctes_injected: Optional[bool] = False
    extra_ctes: Optional[List[ExtraCte]] = None
    field_pre_injected_sql: Optional[str] = Field(None, alias='_pre_injected_sql')
    contract: Optional[Contract24] = Field(None, title='Contract')
    access: Optional[Access] = 'protected'
    constraints: Optional[List[Constraint15]] = None
    version: Optional[Union[str, float]] = None
    latest_version: Optional[Union[str, float]] = None
    deprecation_date: Optional[str] = None
    defer_relation: Optional[DeferRelation4] = None
    primary_key: Optional[List[str]] = None
    time_spine: Optional[TimeSpine1] = None


class Config21(Config20):
    pass


class Constraint16(Constraint):
    pass


class Columns14(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None
    data_type: Optional[str] = None
    constraints: Optional[List[Constraint16]] = None
    quote: Optional[bool] = None
    tags: Optional[List[str]] = None
    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    granularity: Optional[Granularity] = None


class Contract27(Contract3):
    pass


class Disabled5(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    name: str
    resource_type: str = Field('sql_operation', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    alias: str
    checksum: Checksum = Field(..., title='FileHash')
    config: Optional[Config21] = Field(None, title='NodeConfig')
    tags: Optional[List[str]] = None
    description: Optional[str] = ''
    columns: Optional[Dict[str, Columns14]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    docs: Optional[Docs19] = Field(None, title='Docs')
    patch_path: Optional[str] = None
    build_path: Optional[str] = None
    unrendered_config: Optional[Dict[str, Any]] = None
    created_at: Optional[float] = None
    config_call_dict: Optional[Dict[str, Any]] = None
    unrendered_config_call_dict: Optional[Dict[str, Any]] = None
    relation_name: Optional[str] = None
    raw_code: Optional[str] = ''
    language: Optional[str] = 'sql'
    refs: Optional[List[Ref]] = None
    sources: Optional[List[List[str]]] = None
    metrics: Optional[List[List[str]]] = None
    depends_on: Optional[DependsOn12] = Field(None, title='DependsOn')
    compiled_path: Optional[str] = None
    compiled: Optional[bool] = False
    compiled_code: Optional[str] = None
    extra_ctes_injected: Optional[bool] = False
    extra_ctes: Optional[List[ExtraCte]] = None
    field_pre_injected_sql: Optional[str] = Field(None, alias='_pre_injected_sql')
    contract: Optional[Contract27] = Field(None, title='Contract')


class Config22(Config3):
    pass


class Constraint17(Constraint):
    pass


class Columns15(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None
    data_type: Optional[str] = None
    constraints: Optional[List[Constraint17]] = None
    quote: Optional[bool] = None
    tags: Optional[List[str]] = None
    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    granularity: Optional[Granularity] = None


class Disabled6(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    name: str
    resource_type: str = Field('test', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    alias: str
    checksum: Checksum = Field(..., title='FileHash')
    config: Optional[Config22] = Field(None, title='TestConfig')
    tags: Optional[List[str]] = None
    description: Optional[str] = ''
    columns: Optional[Dict[str, Columns15]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    docs: Optional[Docs19] = Field(None, title='Docs')
    patch_path: Optional[str] = None
    build_path: Optional[str] = None
    unrendered_config: Optional[Dict[str, Any]] = None
    created_at: Optional[float] = None
    config_call_dict: Optional[Dict[str, Any]] = None
    unrendered_config_call_dict: Optional[Dict[str, Any]] = None
    relation_name: Optional[str] = None
    raw_code: Optional[str] = ''
    language: Optional[str] = 'sql'
    refs: Optional[List[Ref]] = None
    sources: Optional[List[List[str]]] = None
    metrics: Optional[List[List[str]]] = None
    depends_on: Optional[DependsOn12] = Field(None, title='DependsOn')
    compiled_path: Optional[str] = None
    compiled: Optional[bool] = False
    compiled_code: Optional[str] = None
    extra_ctes_injected: Optional[bool] = False
    extra_ctes: Optional[List[ExtraCte]] = None
    field_pre_injected_sql: Optional[str] = Field(None, alias='_pre_injected_sql')
    contract: Optional[Contract27] = Field(None, title='Contract')
    column_name: Optional[str] = None
    file_key_name: Optional[str] = None
    attached_node: Optional[str] = None
    test_metadata: Optional[TestMetadata] = Field(None, title='TestMetadata')


class Contract29(Contract):
    pass


class Config23(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    enabled: Optional[bool] = True
    alias: Optional[str] = None
    schema_: Optional[str] = Field(None, alias='schema')
    database: Optional[str] = None
    tags: Optional[Union[List[str], str]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    materialized: Optional[str] = 'snapshot'
    incremental_strategy: Optional[str] = None
    batch_size: Optional[Any] = None
    lookback: Optional[Any] = 1
    begin: Optional[Any] = None
    persist_docs: Optional[Dict[str, Any]] = None
    post_hook: Optional[List[PostHookItem]] = Field(None, alias='post-hook')
    pre_hook: Optional[List[PreHookItem]] = Field(None, alias='pre-hook')
    quoting: Optional[Dict[str, Any]] = None
    column_types: Optional[Dict[str, Any]] = None
    full_refresh: Optional[bool] = None
    unique_key: Optional[Union[str, List[str]]] = None
    on_schema_change: Optional[str] = 'ignore'
    on_configuration_change: Optional[OnConfigurationChange] = None
    grants: Optional[Dict[str, Any]] = None
    packages: Optional[List[str]] = None
    docs: Optional[Docs19] = Field(None, title='Docs')
    contract: Optional[Contract29] = Field(None, title='ContractConfig')
    event_time: Optional[Any] = None
    concurrent_batches: Optional[Any] = None
    strategy: Optional[str] = None
    target_schema: Optional[str] = None
    target_database: Optional[str] = None
    updated_at: Optional[str] = None
    check_cols: Optional[Union[str, List[str]]] = None
    snapshot_meta_column_names: Optional[SnapshotMetaColumnNames] = Field(
        None, title='SnapshotMetaColumnNames'
    )
    dbt_valid_to_current: Optional[str] = None


class Constraint18(Constraint):
    pass


class Columns16(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None
    data_type: Optional[str] = None
    constraints: Optional[List[Constraint18]] = None
    quote: Optional[bool] = None
    tags: Optional[List[str]] = None
    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    granularity: Optional[Granularity] = None


class Contract30(Contract3):
    pass


class Contract31(Contract):
    pass


class Config24(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    enabled: Optional[bool] = True
    alias: Optional[str] = None
    schema_: Optional[str] = Field(None, alias='schema')
    database: Optional[str] = None
    tags: Optional[Union[List[str], str]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    materialized: Optional[str] = 'view'
    incremental_strategy: Optional[str] = None
    batch_size: Optional[Any] = None
    lookback: Optional[Any] = 1
    begin: Optional[Any] = None
    persist_docs: Optional[Dict[str, Any]] = None
    post_hook: Optional[List[PostHookItem]] = Field(None, alias='post-hook')
    pre_hook: Optional[List[PreHookItem]] = Field(None, alias='pre-hook')
    quoting: Optional[Dict[str, Any]] = None
    column_types: Optional[Dict[str, Any]] = None
    full_refresh: Optional[bool] = None
    unique_key: Optional[Union[str, List[str]]] = None
    on_schema_change: Optional[str] = 'ignore'
    on_configuration_change: Optional[OnConfigurationChange] = None
    grants: Optional[Dict[str, Any]] = None
    packages: Optional[List[str]] = None
    docs: Optional[Docs19] = Field(None, title='Docs')
    contract: Optional[Contract31] = Field(None, title='ContractConfig')
    event_time: Optional[Any] = None
    concurrent_batches: Optional[Any] = None


class DeferRelation5(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    alias: str
    relation_name: Optional[str]
    resource_type: ResourceType
    name: str
    description: str
    compiled_code: Optional[str]
    meta: Dict[str, Any]
    tags: List[str]
    config: Optional[Config24]


class Disabled7(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    name: str
    resource_type: str = Field('snapshot', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    alias: str
    checksum: Checksum = Field(..., title='FileHash')
    config: Config23 = Field(..., title='SnapshotConfig')
    tags: Optional[List[str]] = None
    description: Optional[str] = ''
    columns: Optional[Dict[str, Columns16]] = None
    meta: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    docs: Optional[Docs19] = Field(None, title='Docs')
    patch_path: Optional[str] = None
    build_path: Optional[str] = None
    unrendered_config: Optional[Dict[str, Any]] = None
    created_at: Optional[float] = None
    config_call_dict: Optional[Dict[str, Any]] = None
    unrendered_config_call_dict: Optional[Dict[str, Any]] = None
    relation_name: Optional[str] = None
    raw_code: Optional[str] = ''
    language: Optional[str] = 'sql'
    refs: Optional[List[Ref]] = None
    sources: Optional[List[List[str]]] = None
    metrics: Optional[List[List[str]]] = None
    depends_on: Optional[DependsOn12] = Field(None, title='DependsOn')
    compiled_path: Optional[str] = None
    compiled: Optional[bool] = False
    compiled_code: Optional[str] = None
    extra_ctes_injected: Optional[bool] = False
    extra_ctes: Optional[List[ExtraCte]] = None
    field_pre_injected_sql: Optional[str] = Field(None, alias='_pre_injected_sql')
    contract: Optional[Contract30] = Field(None, title='Contract')
    defer_relation: Optional[DeferRelation5] = None


class WarnAfter1(WarnAfter):
    pass


class ErrorAfter1(WarnAfter):
    pass


class Freshness1(BaseModel):
    class Config:
        extra = Extra.forbid

    warn_after: Optional[WarnAfter1] = None
    error_after: Optional[ErrorAfter1] = None
    filter: Optional[str] = None


class External1(External):
    pass


class Constraint19(Constraint):
    pass


class Columns17(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: Optional[str] = ''
    meta: Optional[Dict[str, Any]] = None
    data_type: Optional[str] = None
    constraints: Optional[List[Constraint19]] = None
    quote: Optional[bool] = None
    tags: Optional[List[str]] = None
    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    granularity: Optional[Granularity] = None


class Config25(Config11):
    pass


class Disabled8(BaseModel):
    class Config:
        extra = Extra.forbid

    database: Optional[str]
    schema_: str = Field(..., alias='schema')
    name: str
    resource_type: str = Field('source', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    source_name: str
    source_description: str
    loader: str
    identifier: str
    quoting: Optional[Quoting] = Field(None, title='Quoting')
    loaded_at_field: Optional[str] = None
    freshness: Optional[Freshness1] = None
    external: Optional[External1] = None
    description: Optional[str] = ''
    columns: Optional[Dict[str, Columns17]] = None
    meta: Optional[Dict[str, Any]] = None
    source_meta: Optional[Dict[str, Any]] = None
    tags: Optional[List[str]] = None
    config: Optional[Config25] = Field(None, title='SourceConfig')
    patch_path: Optional[str] = None
    unrendered_config: Optional[Dict[str, Any]] = None
    relation_name: Optional[str] = None
    created_at: Optional[float] = None
    unrendered_database: Optional[str] = None
    unrendered_schema: Optional[str] = None


class Config26(Config12):
    pass


class Disabled9(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    resource_type: str = Field('exposure', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    type: Type10
    owner: Owner = Field(..., title='Owner')
    description: Optional[str] = ''
    label: Optional[str] = None
    maturity: Optional[Maturity] = None
    meta: Optional[Dict[str, Any]] = None
    tags: Optional[List[str]] = None
    config: Optional[Config26] = Field(None, title='ExposureConfig')
    unrendered_config: Optional[Dict[str, Any]] = None
    url: Optional[str] = None
    depends_on: Optional[DependsOn12] = Field(None, title='DependsOn')
    refs: Optional[List[Ref]] = None
    sources: Optional[List[List[str]]] = None
    metrics: Optional[List[List[str]]] = None
    created_at: Optional[float] = None


class Filter8(Filter):
    pass


class Measure1(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    filter: Optional[Filter8] = None
    alias: Optional[str] = None
    join_to_timespine: Optional[bool] = False
    fill_nulls_with: Optional[int] = None


class Filter9(Filter):
    pass


class InputMeasure1(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    filter: Optional[Filter9] = None
    alias: Optional[str] = None
    join_to_timespine: Optional[bool] = False
    fill_nulls_with: Optional[int] = None


class Filter10(Filter):
    pass


class Numerator1(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    filter: Optional[Filter10] = None
    alias: Optional[str] = None
    offset_window: Optional[OffsetWindow] = None
    offset_to_grain: Optional[str] = None


class Filter11(Filter):
    pass


class Denominator1(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    filter: Optional[Filter11] = None
    alias: Optional[str] = None
    offset_window: Optional[OffsetWindow] = None
    offset_to_grain: Optional[str] = None


class Window3(Window):
    pass


class Filter12(Filter):
    pass


class Metric1(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    filter: Optional[Filter12] = None
    alias: Optional[str] = None
    offset_window: Optional[OffsetWindow] = None
    offset_to_grain: Optional[str] = None


class Filter13(Filter):
    pass


class BaseMeasure1(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    filter: Optional[Filter13] = None
    alias: Optional[str] = None
    join_to_timespine: Optional[bool] = False
    fill_nulls_with: Optional[int] = None


class Filter14(Filter):
    pass


class ConversionMeasure1(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    filter: Optional[Filter14] = None
    alias: Optional[str] = None
    join_to_timespine: Optional[bool] = False
    fill_nulls_with: Optional[int] = None


class Window4(OffsetWindow):
    pass


class ConversionTypeParams1(BaseModel):
    class Config:
        extra = Extra.forbid

    base_measure: BaseMeasure1 = Field(..., title='MetricInputMeasure')
    conversion_measure: ConversionMeasure1 = Field(..., title='MetricInputMeasure')
    entity: str
    calculation: Optional[Calculation] = 'conversion_rate'
    window: Optional[Window4] = None
    constant_properties: Optional[List[ConstantProperty]] = None


class CumulativeTypeParams1(BaseModel):
    class Config:
        extra = Extra.forbid

    window: Optional[Window4] = None
    grain_to_date: Optional[str] = None
    period_agg: Optional[PeriodAgg] = 'first'


class TypeParams1(BaseModel):
    class Config:
        extra = Extra.forbid

    measure: Optional[Measure1] = None
    input_measures: Optional[List[InputMeasure1]] = None
    numerator: Optional[Numerator1] = None
    denominator: Optional[Denominator1] = None
    expr: Optional[str] = None
    window: Optional[Window3] = None
    grain_to_date: Optional[Granularity] = None
    metrics: Optional[List[Metric1]] = None
    conversion_type_params: Optional[ConversionTypeParams1] = None
    cumulative_type_params: Optional[CumulativeTypeParams1] = None


class Filter15(Filter):
    pass


class Metadata2(Metadata1):
    pass


class Config27(Config13):
    pass


class Disabled10(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    resource_type: str = Field('metric', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    description: str
    label: str
    type: Type11
    type_params: TypeParams1 = Field(..., title='MetricTypeParams')
    filter: Optional[Filter15] = None
    metadata: Optional[Metadata2] = None
    time_granularity: Optional[str] = None
    meta: Optional[Dict[str, Any]] = None
    tags: Optional[List[str]] = None
    config: Optional[Config27] = Field(None, title='MetricConfig')
    unrendered_config: Optional[Dict[str, Any]] = None
    sources: Optional[List[List[str]]] = None
    depends_on: Optional[DependsOn12] = Field(None, title='DependsOn')
    refs: Optional[List[Ref]] = None
    metrics: Optional[List[List[str]]] = None
    created_at: Optional[float] = None
    group: Optional[str] = None


class Where(Filter):
    pass


class QueryParams(BaseModel):
    class Config:
        extra = Extra.forbid

    metrics: List[str]
    group_by: List[str]
    where: Optional[Where]
    order_by: Optional[List[str]] = None
    limit: Optional[int] = None


class ExportAs(Enum):
    table = 'table'
    view = 'view'


class Config28(BaseModel):
    class Config:
        extra = Extra.forbid

    export_as: ExportAs
    schema_name: Optional[str] = None
    alias: Optional[str] = None
    database: Optional[str] = None


class Export(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    config: Config28 = Field(..., title='ExportConfig')
    unrendered_config: Optional[Dict[str, str]] = None


class Metadata3(Metadata1):
    pass


class Cache(BaseModel):
    class Config:
        extra = Extra.forbid

    enabled: Optional[bool] = False


class Config29(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    enabled: Optional[bool] = True
    group: Optional[str] = None
    meta: Optional[Dict[str, Any]] = None
    export_as: Optional[ExportAs] = None
    schema_: Optional[str] = Field(None, alias='schema')
    cache: Optional[Cache] = Field(None, title='SavedQueryCache')


class Disabled11(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    resource_type: str = Field('saved_query', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    query_params: QueryParams = Field(..., title='QueryParams')
    exports: List[Export]
    description: Optional[str] = None
    label: Optional[str] = None
    metadata: Optional[Metadata3] = None
    config: Optional[Config29] = Field(None, title='SavedQueryConfig')
    unrendered_config: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    depends_on: Optional[DependsOn12] = Field(None, title='DependsOn')
    created_at: Optional[float] = None
    refs: Optional[List[Ref]] = None


class NodeRelation(BaseModel):
    class Config:
        extra = Extra.forbid

    alias: str
    schema_name: str
    database: Optional[str] = None
    relation_name: Optional[str] = ''


class Defaults(BaseModel):
    class Config:
        extra = Extra.forbid

    agg_time_dimension: Optional[str] = None


class Type24(Enum):
    foreign = 'foreign'
    natural = 'natural'
    primary = 'primary'
    unique = 'unique'


class Entity(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    type: Type24
    description: Optional[str] = None
    label: Optional[str] = None
    role: Optional[str] = None
    expr: Optional[str] = None


class Agg(Enum):
    sum = 'sum'
    min = 'min'
    max = 'max'
    count_distinct = 'count_distinct'
    sum_boolean = 'sum_boolean'
    average = 'average'
    percentile = 'percentile'
    median = 'median'
    count = 'count'


class AggParams(BaseModel):
    class Config:
        extra = Extra.forbid

    percentile: Optional[float] = None
    use_discrete_percentile: Optional[bool] = False
    use_approximate_percentile: Optional[bool] = False


class NonAdditiveDimension(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    window_choice: Agg
    window_groupings: List[str]


class Measure2(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    agg: Agg
    description: Optional[str] = None
    label: Optional[str] = None
    create_metric: Optional[bool] = False
    expr: Optional[str] = None
    agg_params: Optional[AggParams] = None
    non_additive_dimension: Optional[NonAdditiveDimension] = None
    agg_time_dimension: Optional[str] = None


class Type25(Enum):
    categorical = 'categorical'
    time = 'time'


class ValidityParams(BaseModel):
    class Config:
        extra = Extra.forbid

    is_start: Optional[bool] = False
    is_end: Optional[bool] = False


class TypeParams2(BaseModel):
    class Config:
        extra = Extra.forbid

    time_granularity: Granularity
    validity_params: Optional[ValidityParams] = None


class Metadata4(Metadata1):
    pass


class Dimension(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    type: Type25
    description: Optional[str] = None
    label: Optional[str] = None
    is_partition: Optional[bool] = False
    type_params: Optional[TypeParams2] = None
    expr: Optional[str] = None
    metadata: Optional[Metadata4] = None


class Metadata5(Metadata1):
    pass


class Config30(Config13):
    pass


class Disabled12(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    resource_type: ResourceType
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    model: str
    node_relation: Optional[NodeRelation]
    description: Optional[str] = None
    label: Optional[str] = None
    defaults: Optional[Defaults] = None
    entities: Optional[List[Entity]] = None
    measures: Optional[List[Measure2]] = None
    dimensions: Optional[List[Dimension]] = None
    metadata: Optional[Metadata5] = None
    depends_on: Optional[DependsOn12] = Field(None, title='DependsOn')
    refs: Optional[List[Ref]] = None
    created_at: Optional[float] = None
    config: Optional[Config30] = Field(None, title='SemanticModelConfig')
    unrendered_config: Optional[Dict[str, Any]] = None
    primary_entity: Optional[str] = None
    group: Optional[str] = None


class Format(Enum):
    csv = 'csv'
    dict = 'dict'
    sql = 'sql'


class GivenItem(BaseModel):
    class Config:
        extra = Extra.forbid

    input: str
    rows: Optional[Union[str, List[Dict[str, Any]]]] = None
    format: Optional[Format] = 'dict'
    fixture: Optional[str] = None


class Expect(BaseModel):
    class Config:
        extra = Extra.forbid

    rows: Optional[Union[str, List[Dict[str, Any]]]] = None
    format: Optional[Format] = 'dict'
    fixture: Optional[str] = None


class Overrides(BaseModel):
    class Config:
        extra = Extra.forbid

    macros: Optional[Dict[str, Any]] = None
    vars: Optional[Dict[str, Any]] = None
    env_vars: Optional[Dict[str, Any]] = None


class Config31(BaseModel):
    class Config:
        extra = Extra.allow

    field_extra: Optional[Dict[str, Any]] = Field(None, alias='_extra')
    tags: Optional[Union[str, List[str]]] = None
    meta: Optional[Dict[str, Any]] = None
    enabled: Optional[bool] = True


class Versions(BaseModel):
    class Config:
        extra = Extra.forbid

    include: Optional[List[Union[str, float]]] = None
    exclude: Optional[List[Union[str, float]]] = None


class Disabled13(BaseModel):
    class Config:
        extra = Extra.forbid

    model: str
    given: List[GivenItem]
    expect: Expect = Field(..., title='UnitTestOutputFixture')
    name: str
    resource_type: ResourceType
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    description: Optional[str] = ''
    overrides: Optional[Overrides] = None
    depends_on: Optional[DependsOn12] = Field(None, title='DependsOn')
    config: Optional[Config31] = Field(None, title='UnitTestConfig')
    checksum: Optional[str] = None
    schema_: Optional[str] = Field(None, alias='schema')
    created_at: Optional[float] = None
    versions: Optional[Versions] = None
    version: Optional[Union[str, float]] = None


class Where1(Filter):
    pass


class QueryParams1(BaseModel):
    class Config:
        extra = Extra.forbid

    metrics: List[str]
    group_by: List[str]
    where: Optional[Where1]
    order_by: Optional[List[str]] = None
    limit: Optional[int] = None


class Config32(Config28):
    pass


class Export1(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    config: Config32 = Field(..., title='ExportConfig')
    unrendered_config: Optional[Dict[str, str]] = None


class Metadata6(Metadata1):
    pass


class Config33(Config29):
    pass


class SavedQueries(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    resource_type: str = Field('saved_query', const=True)
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    query_params: QueryParams1 = Field(..., title='QueryParams')
    exports: List[Export1]
    description: Optional[str] = None
    label: Optional[str] = None
    metadata: Optional[Metadata6] = None
    config: Optional[Config33] = Field(None, title='SavedQueryConfig')
    unrendered_config: Optional[Dict[str, Any]] = None
    group: Optional[str] = None
    depends_on: Optional[DependsOn12] = Field(None, title='DependsOn')
    created_at: Optional[float] = None
    refs: Optional[List[Ref]] = None


class Entity1(Entity):
    pass


class NonAdditiveDimension1(NonAdditiveDimension):
    pass


class Measure3(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    agg: Agg
    description: Optional[str] = None
    label: Optional[str] = None
    create_metric: Optional[bool] = False
    expr: Optional[str] = None
    agg_params: Optional[AggParams] = None
    non_additive_dimension: Optional[NonAdditiveDimension1] = None
    agg_time_dimension: Optional[str] = None


class TypeParams3(TypeParams2):
    pass


class Metadata7(Metadata1):
    pass


class Dimension1(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    type: Type25
    description: Optional[str] = None
    label: Optional[str] = None
    is_partition: Optional[bool] = False
    type_params: Optional[TypeParams3] = None
    expr: Optional[str] = None
    metadata: Optional[Metadata7] = None


class Metadata8(Metadata1):
    pass


class Config34(Config13):
    pass


class SemanticModels(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    resource_type: ResourceType
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    model: str
    node_relation: Optional[NodeRelation]
    description: Optional[str] = None
    label: Optional[str] = None
    defaults: Optional[Defaults] = None
    entities: Optional[List[Entity1]] = None
    measures: Optional[List[Measure3]] = None
    dimensions: Optional[List[Dimension1]] = None
    metadata: Optional[Metadata8] = None
    depends_on: Optional[DependsOn12] = Field(None, title='DependsOn')
    refs: Optional[List[Ref]] = None
    created_at: Optional[float] = None
    config: Optional[Config34] = Field(None, title='SemanticModelConfig')
    unrendered_config: Optional[Dict[str, Any]] = None
    primary_entity: Optional[str] = None
    group: Optional[str] = None


class GivenItem1(GivenItem):
    pass


class Expect1(Expect):
    pass


class Config35(Config31):
    pass


class UnitTests(BaseModel):
    class Config:
        extra = Extra.forbid

    model: str
    given: List[GivenItem1]
    expect: Expect1 = Field(..., title='UnitTestOutputFixture')
    name: str
    resource_type: ResourceType
    package_name: str
    path: str
    original_file_path: str
    unique_id: str
    fqn: List[str]
    description: Optional[str] = ''
    overrides: Optional[Overrides] = None
    depends_on: Optional[DependsOn12] = Field(None, title='DependsOn')
    config: Optional[Config35] = Field(None, title='UnitTestConfig')
    checksum: Optional[str] = None
    schema_: Optional[str] = Field(None, alias='schema')
    created_at: Optional[float] = None
    versions: Optional[Versions] = None
    version: Optional[Union[str, float]] = None


class WritableManifest(BaseModel):
    class Config:
        extra = Extra.forbid

    metadata: Metadata = Field(
        ..., description='Metadata about the manifest', title='ManifestMetadata'
    )
    nodes: Dict[str, Union[Nodes, Nodes1, Nodes2, Nodes3, Nodes4, Nodes5, Nodes6, Nodes7]] = Field(
        ..., description='The nodes defined in the dbt project and its dependencies'
    )
    sources: Dict[str, Sources] = Field(
        ..., description='The sources defined in the dbt project and its dependencies'
    )
    macros: Dict[str, Macros] = Field(
        ..., description='The macros defined in the dbt project and its dependencies'
    )
    docs: Dict[str, Docs18] = Field(
        ..., description='The docs defined in the dbt project and its dependencies'
    )
    exposures: Dict[str, Exposures] = Field(
        ..., description='The exposures defined in the dbt project and its dependencies'
    )
    metrics: Dict[str, Metrics] = Field(
        ..., description='The metrics defined in the dbt project and its dependencies'
    )
    groups: Dict[str, Groups] = Field(..., description='The groups defined in the dbt project')
    selectors: Dict[str, Any] = Field(..., description='The selectors defined in selectors.yml')
    disabled: Optional[
        Dict[
            str,
            List[
                Union[
                    Disabled,
                    Disabled1,
                    Disabled2,
                    Disabled3,
                    Disabled4,
                    Disabled5,
                    Disabled6,
                    Disabled7,
                    Disabled8,
                    Disabled9,
                    Disabled10,
                    Disabled11,
                    Disabled12,
                    Disabled13,
                ]
            ],
        ]
    ] = Field(..., description='A mapping of the disabled nodes in the target')
    parent_map: Optional[Dict[str, List[str]]] = Field(
        ..., description='A mapping from\xa0child nodes to their dependencies'
    )
    child_map: Optional[Dict[str, List[str]]] = Field(
        ..., description='A mapping from parent nodes to their dependents'
    )
    group_map: Optional[Dict[str, List[str]]] = Field(
        ..., description='A mapping from group names to their nodes'
    )
    saved_queries: Dict[str, SavedQueries] = Field(
        ..., description='The saved queries defined in the dbt project'
    )
    semantic_models: Dict[str, SemanticModels] = Field(
        ..., description='The semantic models defined in the dbt project'
    )
    unit_tests: Dict[str, UnitTests] = Field(
        ..., description='The unit tests defined in the project'
    )
