name: Publish

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v0.2.5, etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # Required for trusted publishing to PyPI
      contents: write  # Required for creating GitHub releases
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install UV
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --all-extras

    - name: Validate tag version matches package version
      run: |
        # Extract version from tag (remove 'v' prefix)
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        
        # Get version from pyproject.toml
        PACKAGE_VERSION=$(uv run python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")
        
        echo "Tag version: $TAG_VERSION"
        echo "Package version: $PACKAGE_VERSION"
        
        if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
          echo "Error: Tag version ($TAG_VERSION) does not match package version ($PACKAGE_VERSION)"
          exit 1
        fi

    - name: Run tests before publishing
      run: |
        uv run pytest tests/ -v --tb=short

    - name: Build package
      run: |
        uv build

    - name: Validate package
      run: |
        uv publish --dry-run

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # Uses trusted publishing - no API token needed
        # Configure trusted publishing at https://pypi.org/manage/account/publishing/
        print-hash: true

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        generate_release_notes: true
        body: |
          ## Changes in this release
          
          See the [CHANGELOG.md](CHANGELOG.md) for detailed changes.
          
          ## Installation
          
          ```bash
          pip install dbt2lookml==${{ github.ref_name }}
          ```
          
          Or with uv:
          
          ```bash
          uv add dbt2lookml==${{ github.ref_name }}
          ```
        draft: false
        prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}

  test-published-package:
    runs-on: ubuntu-latest
    needs: publish
    
    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Wait for package to be available on PyPI
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/v}
        
        # Wait up to 5 minutes for the package to be available
        for i in {1..30}; do
          if pip index versions dbt2lookml | grep -q "$VERSION"; then
            echo "Package version $VERSION is available on PyPI"
            break
          fi
          echo "Waiting for package to be available on PyPI... (attempt $i/30)"
          sleep 10
        done

    - name: Test installation from PyPI
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        pip install dbt2lookml==$VERSION
        dbt2lookml --help
